### PR TITLE
Update marvel.txt

### PR DESCRIPTION
**Pull request by TheDarkDrake**

### CODE REVIEW

**Comment by TheDarkDrake** [comment]
@srevinsaju @Soul-Breaker please review these

**Comment by srevinsaju** [comment]
I dunno much about marvel. Perhaps @blackxspade @Soul-Breaker.

**Comment by TheDarkDrake** [comment]
> I dunno much about marvel. Perhaps @blackxspade @Soul-Breaker.

lol, ok

**Comment by TheDarkDrake** [comment]
> I dunno much about marvel. Perhaps @blackxspade @Soul-Breaker.

v wait for 2 or 3 more hrs then

**Comment by TheDarkDrake** [comment]
oh wait, @Soul-Breaker did check it out

**Comment by srevinsaju** [comment]
> oh wait, @Soul-Breaker did check it out

Yea? He didnt approve tho

**Review by Mat-Geo — APPROVED** [review]

**Comment by Mat-Geo** [comment]
> > oh wait, @Soul-Breaker did check it out
> 
> Yea? He didnt approve tho

Done, i approved the second commit.

**Comment by srevinsaju** [comment]
hmmmhmm

**Comment by TheDarkDrake** [comment]
hmmmmmmmm

**Comment by sreyasaju** [comment]
hmmmmmhmmmhmm

**Comment by srevinsaju** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by Mat-Geo** [comment]
Anything except the hmm and mm pls. :)

**Comment by TheDarkDrake** [comment]
ummmmmm

**Comment by TheDarkDrake** [comment]
@blackxspade come on......................

**Review by blackxspade — APPROVED** [review]

**Comment by TheDarkDrake** [comment]
at last!!!

**Comment by blackxspade** [comment]
....mmmmmmmmmmm mmmmm

**Pull request merged**
