### PR TITLE
Create harrypotterfiltered.txt

### PR DESCRIPTION
**Pull request by Mat-Geo**

### CODE REVIEW

**Comment by Mat-Geo** [comment]
> _No description provided._

Please change the file name. :)

**Review by srevinsaju — APPROVED** [review]

**Review by blackxspade — APPROVED** [review]

**Review by srevinsaju — APPROVED** [review]

**Comment by sreyasaju** [comment]
Just a suggestion, @srevinsaju @blackxspade , what about adding the following also to the dataset?

-  crookshanks
-  hedwig
-  pigwidgeon
-  grawp 
-  fawkes

**Comment by srevinsaju** [comment]
> Just a suggestion, @srevinsaju @blackxspade , what about adding the following also to the dataset?
> 
> * crookshanks
> * hedwig
> * pigwidgeon
> * grawp
> * fawkes

pls address in another issue

**Comment by Soul-Breaker** [comment]
> Just a suggestion, @srevinsaju @blackxspade , what about adding the following also to the dataset?
> 
> * crookshanks
> * hedwig
> * pigwidgeon
> * grawp
> * fawkes

-grawp
-fawkes 
Are already there. Will make another pull request adding the first 3 names:)

**Pull request merged**
